const mapeamentoDeOrgao = {
    "PGE/MT": "PGE/MT",
    "SEFAZ": "SEFAZ",
    "SEMA": "SEMA",
    "INDEA": "INDEA",
    "PROCON": "PROCON",
    "TJ": "TJ",
    "TCE": "TCE",
    "SES": "SES",
    "SICME": "SICME",
    "AGER/MT": "AGER/MT",
    "FUNDEIC": "FUNDEIC",
    "MP": "MP",
    "SEJUSP": "SEJUSP",
    "CASA CIVIL": "CASA CIVIL",
    "IOMAT": "IOMAT",
    "SEFAZ/TER. INT-TAD": "SEFAZ/TER. INT-TAD",
    "MTGAS": "MTGAS",
    "SEDUC": "SEDUC",
    "SEFAZ/AV. COB. FAZ.": "SEFAZ/AV. COB. FAZ.",
    "SEFAZ/NOTIF.LANÇ.": "SEFAZ/NOTIF.LANÇ.",
    "SEFAZ/DESC. CONT.": "SEFAZ/DESC. CONT.",
    "PRODEIC": "PRODEIC",
    "SECOPA": "SECOPA",
    "SECITEC": "SECITEC",
    "SENCCLT": "SENCCLT",
    "TCD - AGER/MT": "TCD - AGER/MT",
    "SEC": "SEC",
    "DETRAN-MT": "DETRAN-MT",
    "SETASC": "SETASC",
    "SEJUDH": "SEJUDH",
    "SESP": "SESP",
    "SECID": "SECID",
    "SEGES": "SEGES",
    "SEAF": "SEAF",
    "SEDEC": "SEDEC",
    "DESENVOLVE MT": "DESENVOLVE MT",
    "UNEMAT": "UNEMAT",
    "SINFRA": "SINFRA",
    "MTPREV": "MTPREV",
    "FAPEMAT": "FAPEMAT",
    "SEPLAG-MT": "SEPLAG-MT",
    "MTI": "MTI",
    "DP/MT": "DP/MT",
    "CGE-MT": "CGE-MT",
    "CBM-SESP": "CBM-SESP",
};

export default mapeamentoDeOrgao;
